services:
    train-manager-api:
        container_name: train-manager-api
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - type: bind
            source: /var/train_data
            target: /var/train_data
        ports:
          - "8080:8080"
        environment:
          - DATABASE_URL=db
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
          - db
        networks:
          - train-manager-api-network

    db:
        image: postgres:17
        container_name: postgres
        volumes:
          - postgres-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=train_manager
        ports:
          - "5432:5432"
        networks:
          - train-manager-api-network
networks:
    train-manager-api-network:
        driver: bridge
volumes:
    postgres-data: