pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        checkout changelog: false, poll: false, scm: scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins', url: 'https://github.com/tkhs-dev/PBL-team4']])
      }
    }

    stage('build') {
        steps {
            withCredentials([usernamePassword(credentialsId: 'postgres-credential', passwordVariable: 'POSTGRES_PASSWORD', usernameVariable: 'POSTGRES_USER')]) {
                sh 'cd ./train-manager-api ; docker-compose up -d --build'
            }
        }
    }
  }
}