openapi: 3.0.3
info:
  title: Train Manager API
  description: |-
    学習管理API
  version: 1.0.0
tags:
  - name: train
    description: 学習タスク関連
  - name: model
    description: モデル関連
  - name: queue
    description: 学習タスクのキュー関連
paths:
  /train/next:
    get:
      tags:
        - train
      summary: 次の学習タスクを取得する
      description: ''
      responses:
        '200':
          description: 成功。typeによってparameterの構造が変化することに注意。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  deadline:
                    type: integer
                    format: int64
                  task: 
                    $ref: '#/components/schemas/TrainTask'
        '401':
          description: 認証情報が不正
  /train/refresh:
    post:
      tags:
        - train
      summary: 学習タスクの期限を延長する
      description: ''
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: 対象のタスク
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: string
                    format: uuid
                  deadline:
                    type: integer
                    format: int64
                    example: 1732974934257
  /train/register:
    post:
      tags:
        - train
      summary: 学習タスクの結果を登録する
      description: ''
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: 学習タスクのID
                completedAt:
                  type: integer
                  format: int64
                  description: 学習が終了した時間
                modelFile:
                  type: string
                  format: binary
                  description: モデルのバイナリファイル
              required:
                - id
                - completedAt
                - modelFile
      responses:
        '201':
          description: 登録に成功
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError' 
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError' 
  /train/allocatedTasks:
    get:
      tags:
        - train
      summary: 割り当て済みのタスクを取得
      description: ''
      parameters:
        - name: client_name
          in: query
          description: 対象のクライアント
          required: false
          schema:
            type: string
        - name: contain_completed
          in: query
          description: 終了したタスクを含めるか
          required: false
          schema:
            type: boolean
            default: false
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 0
        
      responses:
        '200':
          description: 成功
          content: 
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllocatedTask' 
                

components:
  schemas:
    TrainTask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        base_model_id:
          type: string
          format: uuid
          description: 学習元となるモデルのID
        type:
          type: string
          description: タスクの種類
          example: supervised
          enum:
            - supervised
        parameter:
          oneOf:
            - $ref: '#/components/schemas/ParameterSupervised'
            - $ref: '#/components/schemas/ParameterReinforcedTraining'
    ParameterSupervised:
      type: object
      description: 教師あり学習時のパラメーター
      properties:
        player_id:
          type: string
          description: 教師となるプレイヤーID
          example: player
        game_id:
          type: string
          description: 教師となるゲームのID
          example: game_id

    ParameterReinforcedTraining:
      type: object
      description: 強化学習時のパラメーター
      properties:
        num_epoch:
          type: integer
          format: int32
          description: 学習のエポック数
          example: 100

    AllocatedTask:
      type: object
      description: 割り当て済みのタスク
      properties:
        id:
          type: string
          format: uuid
        allocated_at:
          type: integer
          format: int64
          description: タスクが割り当てられた時間
        allocated_client:
          type: string
          description: 割り当てられたクライアント
        deadline:
          type: integer
          format: int64
          description: 学習結果の提出期限
          example: 1732974934257
        status:
          type: string
          description: タスクの状態
          enum:
            - completed
            - processing
            - timeup
            - error
        status_changed_at:
          type: integer
          format: int64
          description: 最後にステータスが変化した時間
        task:
          $ref : '#/components/schemas/TrainTask'

    ApiError:
      type: object
      properties:
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []