openapi: 3.0.3
info:
  title: Train Manager API
  description: |-
    学習管理API
  version: 1.0.0
tags:
  - name: assignment
    description: 割り当てタスク関連
  - name: model
    description: モデル関連
  - name: queue
    description: タスクのキュー関連
  - name: task
    description: タスク関連
paths:
  /assignments/next:
    get:
      tags:
        - assignment
      summary: 次のタスクを取得する
      description: ''
      responses:
        '200':
          description: 成功。typeによってparameterの構造が変化することに注意。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  deadline:
                    type: integer
                    format: int64
                  task: 
                    $ref: '#/components/schemas/TrainTask'
        '401':
          description: 認証情報が不正
  /assignments/{id}/refresh:
    post:
      tags:
        - assignment
      summary: タスクの期限を延長する
      description: 'タスクを割り当てられたクライアントのみが操作可能'
      parameters:
        - name: id
          in: path
          description: タスクの割り当てID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: 
                  id:
                    type: string
                    format: uuid
                  deadline:
                    type: integer
                    format: int64
                    example: 1732974934257
  /assignments/{id}/register:
    post:
      tags:
        - assignment
      summary: タスクの結果を登録する
      description: 'タスクを割り当てられたクライアントのみが操作可能'
      parameters:
        - name: id
          in: path
          description: タスクの割り当てID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: 学習タスクのID
                completedAt:
                  type: integer
                  format: int64
                  description: 学習が終了した時間
                modelFile:
                  type: string
                  format: binary
                  description: モデルのバイナリファイル
              required:
                - id
                - completedAt
                - modelFile
      responses:
        '201':
          description: 登録に成功
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError' 
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError' 
  /assignments:
    get:
      tags:
        - assignment
      summary: タスク一覧を取得
      description: ''
      parameters:
        - name: client_name
          in: query
          description: 対象のクライアント
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: 検索対象のステータス
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - completed
                - processing
                - timeup
                - error
            default: [completed, processing, timeup, error]
          style: matrix
          explode: false
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 0
        
      responses:
        '200':
          description: 成功
          content: 
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assignment'

  /models:
    get:
      tags:
        - model
      summary: モデル一覧を取得
      description: ''
      parameters:
        - name: parent_id
          in: query
          description: 親モデルのID
          required: false
          schema:
            type: string
        - name: tracking_id
          in: query
          description: モデルの系統を示すID
          required: false
          schema:
              type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 0
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'

  /models/{id}:
    get:
      tags:
        - model
      summary: モデルを取得
      description: ''
      parameters:
        - name: id
          in: path
          description: モデルのID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
        '404':
          description: モデルが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /queue:
    get:
      tags:
        - queue
      summary: キューの状態を取得
      description: ''
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    index:
                      type: integer
                      format: int32
                    task:
                      $ref: '#/components/schemas/TrainTask'

    post:
      tags:
        - queue
      summary: タスクをキューに追加
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  $ref: '#/components/schemas/TrainTask'
      responses:
        '201':
          description: キューに追加成功
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /tasks:
    get:
      tags:
          - task
      summary: タスク一覧を取得
      description: ''
      parameters:
        - name: contain_completed
          in: query
          schema:
            type: boolean
            default: false
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 0
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainTask'

  /tasks/generators:
    get:
      tags:
          - task
      summary: タスクの生成器一覧を取得
      description: ''
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    index:
                      type: integer
                      format: int32
                    generator:
                      $ref: '#/components/schemas/TaskGenerator'

    post:
      tags:
        - task
      summary: タスクの生成器を登録
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskGenerator'
      responses:
        '201':
          description: 成功
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    delete:
        tags:
            - task
        summary: タスクの生成器を削除
        description: ''
        parameters:
            - name: index
              in: query
              required: true
              schema:
                type: integer
                format: int32
        responses:
            '200':
              description: 成功
            '400':
              description: Bad Request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ApiError'
            '500':
              description: Internal Error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ApiError'

components:
  schemas:
    TrainTask:
      type: object
      properties:
        id:
          type: string
          format: uuid

        completed:
          type: boolean
          description: タスクが完了したかどうか

        base_model_id:
          type: string
          format: uuid
          description: 学習元となるモデルのID

        type:
          type: string
          description: タスクの種類
          example: supervised
          enum:
            - supervised
        parameter:
          oneOf:
            - $ref: '#/components/schemas/ParameterSupervised'
            - $ref: '#/components/schemas/ParameterReinforcedTraining'
    ParameterSupervised:
      type: object
      description: 教師あり学習時のパラメーター
      properties:
        player_id:
          type: string
          description: 教師となるプレイヤーID
          example: player
        game_id:
          type: array
          items:
            type: string
            description: 教師となるゲームのID
            example: game_id

    ParameterReinforcedTraining:
      type: object
      description: 強化学習時のパラメーター
      properties:
        num_epoch:
          type: integer
          format: int32
          description: 学習のエポック数
          example: 100

    Assignment:
      type: object
      description: 割り当て済みのタスク
      properties:
        id:
          type: string
          format: uuid
        assigned_at:
          type: integer
          format: int64
          description: タスクが割り当てられた時間
        client:
          type: string
          description: 担当するクライアント
        deadline:
          type: integer
          format: int64
          description: 学習結果の提出期限
          example: 1732974934257
        status:
          type: string
          description: タスクの状態
          enum:
            - completed
            - processing
            - timeup
            - error
        status_changed_at:
          type: integer
          format: int64
          description: 最後にステータスが変化した時間
        task:
          $ref : '#/components/schemas/TrainTask'

    Model:
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: string
          description: モデルのバージョン
        parent_id:
          type: string
          description: 親モデルのID
        tracking_id:
          type: string
          description: モデルの系統を示すID
        sequence:
          type: integer
          format: int32
          description: モデルの系統の中での通し番号
        task_id:
          type: string
          format: uuid
          description: モデルが作成されたタスクのID
        created_at:
          type: integer
          format: int64
          description: モデルが作成された時間
          example: 1732974934257

    TaskGenerator:
      type: object
      properties:
        type:
          type: string
          description: タスクの種類
          example: supervised
          enum:
            - supervised
            - reinforced
        parameter:
          oneOf:
            - type: object
              properties:
                player_id:
                  type: string
                  description: 教師となるプレイヤーID
                  example: player
            - $ref: '#/components/schemas/ParameterReinforcedTraining'
    ApiError:
      type: object
      properties:
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []