ktor:
  application:
    modules:
      - ac.osaka_u.ics.pbl.ApplicationKt.module
  deployment:
    port: 8080
    debug: true
    staticRoot: "/var/train_data"
    database:
      url: "db"
      port: 5432
      user: "postgres"
      password: "postgres"
