ktor:
  application:
    modules:
      - ac.osaka_u.ics.pbl.ApplicationKt.module
  deployment:
    port: 8080
    debug: true
    staticRoot: "/var/train_data"
    database:
      url: "$DATABASE_URL:localhost"
      port: "$DATABASE_PORT:5432"
      user: $POSTGRES_USER
      password: $POSTGRES_PASSWORD
